package v1beta1

import "net"

type LoadBalancer struct {
	// ID of the load balancer, generated by the cloud provider
	// +optional
	ID int

	// Algorithm used
	// +optional
	Algorithm string

	// Type of the load balancer
	// +optional
	Type string

	// Public IPv4 address
	// +optional
	IPv4 net.IP

	// Public IPv6 address
	// +optional
	IPv6 net.IP

	// Port where the load balancer will bind to
	// +optional
	Port int
}
